# Generated by Django 4.0.6 on 2022-07-15 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='protectedblog',
            name='attributed_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='protectedblog',
            name='author',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
