# Generated by Django 4.0.6 on 2022-08-16 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_protectedblog_attributed_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtectedBlog2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=200)),
                ('strapline', models.TextField(blank=True, max_length=500)),
                ('is_encrypted', models.BooleanField()),
                ('is_signed', models.BooleanField()),
                ('rsa_signature', models.TextField(blank=True, max_length=200)),
                ('blog_content', models.TextField()),
                ('author', models.CharField(blank=True, max_length=100)),
                ('attributed_name', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
